### ISSUE TITLE
Continuous support

### ISSUE THREAD

**Issue by Tymek** [Tymek/ra-language-polish#3]
I made some improvements
- Typescript support
- Renovate Bot for updating dependencies
- Travis CI build with weekly cron
- fixed missing strings
- removed not working image from README
- other minor changes

would you be interested in merging it?
BTW, is this translation still sponsored and supported, as README states?

**Comment by Tymek** [comment]
package `@scrlk/ra-language-polish` published for reference

**Comment by tskorupka** [comment]
README.md file was copied from other repository it is not sponsored by marmelab, this should be removed
